{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "24a9cbc9",
   "metadata": {},
   "source": [
    "Harika, o zaman **yaptığın tüm süreci ve son eklemeyi tek bir akış hâlinde** özetleyelim. Bu, hem ne yaptığını hem de bundan sonra nasıl kullanacağını net gösterir.\n",
    "\n",
    "---\n",
    "\n",
    "# 1️⃣ Ortamı hazırladın (M2 Mac + Python venv)\n",
    "\n",
    "**Ne yaptın:**\n",
    "\n",
    "1. Mevcut environment’ı kapattın:\n",
    "\n",
    "```bash\n",
    "deactivate\n",
    "```\n",
    "\n",
    "2. Temiz bir virtual environment oluşturdun:\n",
    "\n",
    "```bash\n",
    "python3 -m venv my_steps_env\n",
    "source my_steps_env/bin/activate\n",
    "```\n",
    "\n",
    "3. Paketleri yükledin ve uyumlu hale getirdin:\n",
    "\n",
    "```bash\n",
    "pip install --upgrade pip setuptools wheel\n",
    "pip install torch torchvision torchaudio      # PyTorch ≥2.6, M2 Metal uyumlu\n",
    "pip install \"numpy<2\"                         # NumPy uyumlu\n",
    "pip install sentence-transformers transformers python-dotenv pinecone grpcio protobuf googleapis-common-protos\n",
    "pip install openai                             # opsiyonel, artık lokal LLM ile de çalışıyor\n",
    "```\n",
    "\n",
    "**Neden:**\n",
    "\n",
    "* PyTorch ≥2.6 → M2 Mac Metal GPU uyumlu\n",
    "* NumPy <2 → sentence-transformers uyumu\n",
    "* Pinecone v3 + gRPC çalışması için protobuf ve grpcio gerekli\n",
    "\n",
    "---\n",
    "\n",
    "# 2️⃣ .env dosyası ile Pinecone API key ekledin\n",
    "\n",
    "```\n",
    "PINECONE_API_KEY=senin_api_key\n",
    "```\n",
    "\n",
    "* Pinecone’a bağlanabilmek için API key şart\n",
    "* `load_dotenv()` ile script’ine çekiyorsun\n",
    "\n",
    "---\n",
    "\n",
    "# 3️⃣ Pinecone index oluşturup kontrol ettin\n",
    "\n",
    "```python\n",
    "from pinecone import Pinecone, ServerlessSpec\n",
    "pc = Pinecone(api_key=os.getenv(\"PINECONE_API_KEY\"))\n",
    "\n",
    "if \"rag-demo\" not in pc.list_indexes().names():\n",
    "    pc.create_index(\n",
    "        name=\"rag-demo\",\n",
    "        dimension=384,         # BGE-small embedding boyutu\n",
    "        metric=\"cosine\",\n",
    "        spec=ServerlessSpec(cloud=\"aws\", region=\"us-east-1\")\n",
    "    )\n",
    "```\n",
    "\n",
    "* Index = veri tabanı, embedding’leri burada saklıyorsun\n",
    "* Boyut (dimension) embedding modeli ile aynı olmalı\n",
    "\n",
    "---\n",
    "\n",
    "# 4️⃣ Embedding modelini yükledin\n",
    "\n",
    "```python\n",
    "from sentence_transformers import SentenceTransformer\n",
    "import torch\n",
    "\n",
    "device = \"mps\" if torch.backends.mps.is_available() else \"cpu\"\n",
    "model = SentenceTransformer(\"BAAI/bge-small-en\", device=device)\n",
    "```\n",
    "\n",
    "* BGE-small → metinleri vektöre (embedding) çeviriyor\n",
    "* M2 Metal GPU varsa kullanıyor, yoksa CPU fallback\n",
    "\n",
    "---\n",
    "\n",
    "# 5️⃣ Dokümanları embed edip Pinecone’a upsert ettin\n",
    "\n",
    "```python\n",
    "docs = [(\"doc1\", \"FastAPI is a Python web framework.\"),\n",
    "        (\"doc2\", \"Docker containers are used for packaging apps.\")]\n",
    "\n",
    "vectors = [(doc_id, model.encode(text).tolist(), {\"text\": text}) for doc_id, text in docs]\n",
    "pc.upsert(index_name=\"rag-demo\", vectors=vectors)\n",
    "```\n",
    "\n",
    "* Metadata ile metin içeriğini sakladın\n",
    "* Artık query ile eşleşme bulabilir hale geldi\n",
    "\n",
    "---\n",
    "\n",
    "# 6️⃣ Query yaptın ve benzer dokümanları aldın\n",
    "\n",
    "```python\n",
    "query = \"What is FastAPI?\"\n",
    "q_vec = model.encode(query).tolist()\n",
    "res = pc.query(index_name=\"rag-demo\", vector=q_vec, top_k=2, include_metadata=True)\n",
    "print(res)\n",
    "```\n",
    "\n",
    "* `score` → dokümanın query ile benzerliği\n",
    "* `metadata` → orijinal metin\n",
    "\n",
    "---\n",
    "\n",
    "# 7️⃣ RAG pipeline: Query → Context → Prompt → LLM response (yeni ekleme)\n",
    "\n",
    "Sen OpenAI kullanmak yerine **Flan-T5 (seq2seq)** kullandın:\n",
    "\n",
    "```python\n",
    "from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, pipeline\n",
    "\n",
    "model_name = \"google/flan-t5-large\"\n",
    "tokenizer = AutoTokenizer.from_pretrained(model_name)\n",
    "model = AutoModelForSeq2SeqLM.from_pretrained(model_name)\n",
    "llm_pipe = pipeline(\"text2text-generation\", model=model, tokenizer=tokenizer, max_length=512)\n",
    "\n",
    "# Context oluştur\n",
    "context = \"\\n\".join([match['metadata']['text'] for match in res['matches']])\n",
    "prompt = \"Answer based on context:\\n\" + context + \"\\nQuestion: \" + query\n",
    "\n",
    "# LLM response\n",
    "answer = llm_pipe(prompt)[0]['generated_text']\n",
    "\n",
    "print(\"\\n--- Context from Pinecone ---\\n\", context)\n",
    "print(\"\\n--- LLM Answer ---\\n\", answer)\n",
    "```\n",
    "\n",
    "**Ne oldu:**\n",
    "\n",
    "* Pinecone’dan top_k dokümanları aldın\n",
    "* Context oluşturup prompt hazırlandı\n",
    "* Flan-T5 modelinden yanıt üretildi\n",
    "* Artık **tamamen ücretsiz ve local LLM** ile RAG pipeline çalışıyor\n",
    "\n",
    "---\n",
    "\n",
    "# 8️⃣ Bundan sonra nasıl kullanacaksın\n",
    "\n",
    "1. **FastAPI ile API oluştur:**\n",
    "\n",
    "   * Kullanıcı query gönderir → embedding → Pinecone → top_k → context → Flan-T5 → yanıt döner\n",
    "\n",
    "2. **Dockerize et:**\n",
    "\n",
    "   * Tek script’i container içine koy → RAG service olarak deploy\n",
    "\n",
    "3. **Dokümanları artır ve test et:**\n",
    "\n",
    "   * Farklı namespace’ler ile Pinecone limitlerini aşmadan büyüt\n",
    "\n",
    "---\n",
    "\n",
    "# 🔹 Özet\n",
    "\n",
    "* Ortam → hazır ve uyumlu\n",
    "* Pinecone → vektör depolama ve retrieval\n",
    "* Embedding → BGE-small\n",
    "* LLM → Flan-T5 (local, ücretsiz)\n",
    "* Pipeline → query → embedding → Pinecone → context → prompt → LLM response\n",
    "\n",
    "Bu noktada pipeline **çalışıyor ve test edilebilir** durumda.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ba4230c3",
   "metadata": {},
   "source": []
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
